---
- hosts: web
  become: yes
  vars:
    app_server_ip: 172.31.21.145

  tasks:
  - name: "add an apt key for mongoDB"
    command: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927"

  - name: "creating list file"
    command: "echo 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list"

  - name: "installing mongoDB"
    apt:
      name: mongodb-org
      state: present
  
  - name: "starting mongo DB"
    systemd:
      name: mongod
      enabled: yes
      state: started

  - name: "allow specific ips"
    ufw:
      rule: allow
      from_ip: "{{app_server_ip}}/32"
      to_port: 27017